<?php

/**
 * Implements hook_menu().
 */
function islandora_remote_object_copy_menu() {
  $items = array();

  $items['admin/config/development/islandora-remote-object-copy-settings'] = array(
    'title' => 'Islandora Remote Object Copy Settings',
    'description' => 'Settings for the Islandora Remote Object Copy.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_remote_object_copy_copy_settings'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/config/development/islandora-remote-object-copy-single'] = array(
    'title' => 'Islandora Remote Object Copy Single',
    'description' => 'Copy a remote fedora object into your islandora fedora.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_remote_object_copy_copy_single'),
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/config/development/islandora-remote-object-copy-collection'] = array(
    'title' => 'Islandora Remote Object Copy Collection',
    'description' => 'Copy records from a collection.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_remote_object_copy_copy_collection'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Settings form for Remote Object Copy.
 */
function islandora_remote_object_copy_copy_settings($form, &$form_state) {
  $form['islandora_remote_object_copy_uri'] = array(
    '#type' => 'textfield',
    '#title' => t('Fedora URL'),
    '#required' => TRUE,
    '#default_value' => variable_get('islandora_remote_object_copy_uri', ''),
  );

  $form['islandora_remote_object_copy_username'] = array(
    '#type' => 'textfield',
    '#title' => t('Fedora Username'),
    '#required' => TRUE,
    '#default_value' => variable_get('islandora_remote_object_copy_username', ''),
  );

  $form['islandora_remote_object_copy_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Fedora Password'),
    '#required' => TRUE,
    '#default_value' => variable_get('islandora_remote_object_copy_password', ''),
  );

  return system_settings_form($form);
}

/**
 * Form to copy collection from remote fedora repo.
 */
function islandora_remote_object_copy_copy_collection($form, &$form_state) {
  $form['collection'] = array(
    '#type' => 'textfield',
    '#title' => t('Collection'),
    '#description' => t('Collection from which to copy objects over'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Submits Form to copy collection from remote fedora repo.
 */
function islandora_remote_object_copy_copy_collection_submit($form, &$form_state) {
  $values = $form_state['values'];
  $url = variable_get('islandora_remote_object_copy_uri', '');
  $fedora_account = new stdClass();
  $fedora_account->user = variable_get('islandora_remote_object_copy_username', '');
  $fedora_account->pass = variable_get('islandora_remote_object_copy_password', '');
  $collection_pid = $values['collection'];

  $children = islandora_remote_object_copy_get_collection_children($url, $fedora_account, $collection_pid);

  $batch = array(
    'operations' => array(),
    'finished' => 'islandora_remote_object_copy_batch_copy_collection_finished',
    'title' => t('Importing collection...'),
    'init_message' => t('Preparing to import collection...'),
    'progress_message' => t('Importing collection...'),
    'error_message' => t('Collection could not be imported.'),
  );

  foreach ($children as $child) {
    $batch['operations'][] = array(
      'islandora_remote_object_copy_batch_copy_collection_object', array(
        $url,
        $fedora_account,
        $collection_pid,
        $child,
      ),
    );
  }

  batch_set($batch);
}

/**
 * Batch function for finishing collection copy.
 */
function islandora_remote_object_copy_batch_copy_collection_finished() {
  drupal_set_message(t('Successfully imported collection!'));
}

/**
 * Primary copy form.
 */
function islandora_remote_object_copy_copy_single($form, &$form_state) {
  $form['parent_collection'] = array(
    '#type' => 'textfield',
    '#title' => t('Parent Collection'),
    '#description' => t('Parent collection to attach object to.'),
    '#required' => TRUE,
  );

  $form['fedora_pid'] = array(
    '#type' => 'textfield',
    '#title' => t('Fedora Pid'),
    '#description' => t('The Fedora Pid to look for and copy over.'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

/**
 * Submits single object copy form.
 */
function islandora_remote_object_copy_copy_single_submit($form, &$form_state) {
  $values = $form_state['values'];
  $url = variable_get('islandora_remote_object_copy_uri', '');
  $fedora_account = new stdClass();
  $fedora_account->user = variable_get('islandora_remote_object_copy_username', '');
  $fedora_account->pass = variable_get('islandora_remote_object_copy_password', '');
  $parent_collection = $values['parent_collection'];
  $fedora_pid = $values['fedora_pid'];
  islandora_remote_object_copy_copy_single_object($url, $fedora_account, $parent_collection, $fedora_pid);
}

/**
 * Returns all children that belong to a fedora collection.
 */
function islandora_remote_object_copy_get_collection_children($url, $fedora_account, $collection_pid) {
  module_load_include('inc', 'islandora', 'includes/tuque');
  module_load_include('inc', 'islandora', 'includes/tuque_wrapper');
  module_load_include('inc', 'islandora_remote_object_copy', 'includes/UncachedFedoraRepository');
  module_load_include('inc', 'islandora_compound_object', 'includes/manage.form');

  $connection = new RepositoryConnection($url, $fedora_account->user, $fedora_account->pass);
  $api = new FedoraApi($connection);
  $repository = new UncachedFedoraRepository($api, new SimpleCache());
  $fedora_object = $repository->getObject($collection_pid);
  $children = islandora_basic_collection_get_member_objects($fedora_object, 0, 10000, 'manage');
  $collection_children = array();
  foreach ($children as $child) {
    if (is_array($child)) {
      foreach ($child as $child_object) {
        $collection_children[] = $child_object['object']['value'];
      }
    }
  }
  return $collection_children;
}

/**
 * Wrapper function to copy single object.
 */
function islandora_remote_object_copy_batch_copy_collection_object($url, $fedora_account, $parent_collection, $fedora_pid, &$context) {
  islandora_remote_object_copy_copy_single_object($url, $fedora_account, $parent_collection, $fedora_pid);
}

/**
 * Copies single object from secondary fedora repository to primary fedora repository.
 */
function islandora_remote_object_copy_copy_single_object($url, $fedora_account, $parent_collection, $fedora_pid) {
  @set_time_limit(3600*6);
  module_load_include('inc', 'islandora', 'includes/tuque');
  module_load_include('inc', 'islandora', 'includes/tuque_wrapper');
  module_load_include('inc', 'islandora_remote_object_copy', 'includes/UncachedFedoraRepository');
  module_load_include('inc', 'islandora_compound_object', 'includes/manage.form');

  $connection = new RepositoryConnection($url, $fedora_account->user, $fedora_account->pass);
  $api = new FedoraApi($connection);
  $repository = new UncachedFedoraRepository($api, new SimpleCache());
  $fedora_object = $repository->getObject($fedora_pid);
  $compound = FALSE;
  if ($fedora_object['RELS-INT']) {
    $rels_int = $fedora_object['RELS-INT']->content;
    if (substr_count($rels_int, 'rdf:about') > 1) {
      $compound = TRUE;
    }
  }
  if ($compound) {
    $islandora_object = islandora_remote_object_copy_create_compound_object($fedora_object, $parent_collection);
    drupal_set_message(t('Created Islandora Object @islandora_object', array('@islandora_object' => $islandora_object->id)));
    $counter = 1;
    $context = array();
    foreach ($fedora_object as $datastream) {
      $child_object = islandora_remote_object_copy_create_compound_object_item($datastream, $islandora_object, $fedora_object, $parent_collection);
      if (!empty($child_object)) {
        drupal_set_message(t('Created Child Islandora Object @islandora_object', array('@islandora_object' => $child_object->id)));
        islandora_compound_object_update_sequence($islandora_object->id, $child_object->id, $counter, $context);
        $counter++;
      }
    }
  }
}

/**
 * Creates compound object.
 */
function islandora_remote_object_copy_create_compound_object($fedora_object, $parent_collection) {
  $tuque = islandora_get_tuque_connection();
  $islandora_object = islandora_object_load($fedora_object->id);
  $object_properties = array(
    'state',
    'createdDate',
    'lastModifiedDate',
    'label',
    'owner',
    'logMessage',
  );
  $content_models = array(
    'islandora:compoundCModel',
    'fedora-system:FedoraObject-3.0',
  );
  $datastreams = array(
    'MODS',
    'DC',
    'TN',
  );
  if (empty($islandora_object)) {
    $islandora_object = $tuque->repository->constructObject($fedora_object->id);
    foreach ($object_properties as $property) {
      if (isset($fedora_object->$property)) {
        $islandora_object->$property = $fedora_object->$property;
      }
    }
    foreach ($content_models as $content_model) {
      $islandora_object->relationships->add(FEDORA_MODEL_URI, 'hasModel', $content_model);
    }
    $islandora_object->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $parent_collection);
    foreach ($datastreams as $datastream) {
      if ($fedora_object[$datastream]) {
        $fedora_ds = $fedora_object[$datastream];
        $ds = $islandora_object->constructDatastream($datastream);
        $ds->label = $fedora_ds->label;
        $ds->mimetype = $fedora_ds->mimetype;
        $ds->control_group = 'M';
        $ds->setContentFromString($fedora_ds->content);
        $islandora_object->ingestDatastream($ds);
      }
    }
    islandora_add_object($islandora_object);
  }
  else {
    drupal_set_message('object exists' . $fedora_object->id);
  }
  return $islandora_object;
}

/**
 * Creates compound object item.
 */
function islandora_remote_object_copy_create_compound_object_item($fedora_object_datastream, $islandora_object, $fedora_object, $parent_collection) {
  $tuque = islandora_get_tuque_connection();
  $fedora_datastream = $fedora_object[$fedora_object_datastream->id];
  $islandora_child_object = NULL;

  $mime_type = NULL;
  if (!empty($fedora_object['RELS-INT'])) {
    $xml = $fedora_object['RELS-INT']->content;
    if (strpos($xml, 'rdf:about="info:fedora/' . $fedora_object->id . '/' . $fedora_datastream->id) !== FALSE) {
      $mime_type = $fedora_datastream->mimetype;
    }
  }

  // Determine content model and content datastream
  if ($mime_type == 'application/pdf') {
    $content_models = array(
      'islandora:sp_pdf',
    );
    $content_datastream = 'OBJ';
  }

  if (!empty($content_models)) {
    $namespace = explode(':', $fedora_object->id);
    $content_models[] = 'fedora-system:FedoraObject-3.0';
    $object_properties = array(
      'state',
      'createdDate',
      'lastModifiedDate',
      'owner',
      'logMessage',
    );
    $datastreams = array(
      'MODS',
      'DC'
    );
    $islandora_child_object = $tuque->repository->constructObject($namespace[0]);
    $islandora_child_object->label = $fedora_datastream->label;
    foreach ($object_properties as $property) {
      if (isset($fedora_object->$property)) {
        $islandora_child_object->$property = $fedora_object->$property;
      }
    }
    foreach ($content_models as $content_model) {
      $islandora_child_object->relationships->add(FEDORA_MODEL_URI, 'hasModel', $content_model);
    }
    $rels_predicate = variable_get('islandora_compound_object_relationship', 'isConstituentOf');
    $islandora_child_object->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', $parent_collection);
    $islandora_child_object->relationships->add('info:fedora/fedora-system:def/relations-external#', $rels_predicate, $islandora_object->id);
    foreach ($datastreams as $datastream) {
      if ($fedora_object[$datastream]) {
        $fedora_ds = $fedora_object[$datastream];
        $ds = $islandora_child_object->constructDatastream($datastream);
        $ds->label = $fedora_ds->label;
        $ds->mimetype = $fedora_ds->mimetype;
        $ds->control_group = 'M';
        $ds->setContentFromString($fedora_ds->content);
        $islandora_child_object->ingestDatastream($ds);
      }
    }
    $ds = $islandora_child_object->constructDatastream($content_datastream);
    $ds->label = $fedora_datastream->label;
    $ds->mimetype = $fedora_datastream->mimetype;
    $ds->control_group = 'M';
    $ds->setContentFromString($fedora_datastream->content);
    $islandora_child_object->ingestDatastream($ds);
    islandora_add_object($islandora_child_object);
  }
  return $islandora_child_object;
}
